import subprocess

def create_fix_branch():

    subprocess.run(
        ["git", "checkout", "-b", "auto-fix-branch"],
        check=False
    )

    subprocess.run(
        ["git", "add", "."],
        check=True
    )

    subprocess.run(
        ["git", "commit", "-m", "Auto fix generated by AI"],
        check=False
    )

    print("Git branch and commit created")